name: Test Angular Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-library:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Detect Changed Library
        id: detect-library
        run: |
          LIBRARY=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | awk -F'/' '{print $2}' | sort -u | grep -E '^projects/' | sed 's/projects\///g' | head -n 1)
          echo "Library detected: $LIBRARY"
          echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV

      - name: Run Tests (If Library Changed)
        if: env.LIBRARY != ''
        run: npx jest --config projects/${{ env.LIBRARY }}/jest.config.js
